{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "gather": {
     "logged": 1598275788035
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Workspace name: quick-starts-ws-124346\n",
      "Azure region: southcentralus\n",
      "Subscription id: 25e9e549-bc6b-4c63-bae8-181a9aa56fa7\n",
      "Resource group: aml-quickstarts-124346\n"
     ]
    }
   ],
   "source": [
    "from azureml.core import Workspace, Experiment\n",
    "\n",
    "#ws = Workspace.get(name=\"udacity-project\")\n",
    "ws = Workspace.from_config()\n",
    "exp = Experiment(workspace=ws, name=\"udacity-project\")\n",
    "\n",
    "print('Workspace name: ' + ws.name, \n",
    "      'Azure region: ' + ws.location, \n",
    "      'Subscription id: ' + ws.subscription_id, \n",
    "      'Resource group: ' + ws.resource_group, sep = '\\n')\n",
    "\n",
    "run = exp.start_logging()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "gather": {
     "logged": 1598275788675
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Compute target exists\n",
      "{'currentNodeCount': 0, 'targetNodeCount': 0, 'nodeStateCounts': {'preparingNodeCount': 0, 'runningNodeCount': 0, 'idleNodeCount': 0, 'unusableNodeCount': 0, 'leavingNodeCount': 0, 'preemptedNodeCount': 0}, 'allocationState': 'Steady', 'allocationStateTransitionTime': '2020-11-03T13:31:00.217000+00:00', 'errors': None, 'creationTime': '2020-11-03T10:24:31.177245+00:00', 'modifiedTime': '2020-11-03T10:24:46.584428+00:00', 'provisioningState': 'Succeeded', 'provisioningStateTransitionTime': None, 'scaleSettings': {'minNodeCount': 0, 'maxNodeCount': 4, 'nodeIdleTimeBeforeScaleDown': 'PT120S'}, 'vmPriority': 'Dedicated', 'vmSize': 'STANDARD_D2_V2'}\n"
     ]
    }
   ],
   "source": [
    "from azureml.core.compute import ComputeTarget, AmlCompute\n",
    "from azureml.core.compute_target import ComputeTargetException\n",
    "\n",
    "# TODO: Create compute cluster\n",
    "# Use vm_size = \"Standard_D2_V2\" in your provisioning configuration.\n",
    "# max_nodes should be no greater than 4.\n",
    "\n",
    "# choose a name for your cluster\n",
    "cluster_name = \"cpu-cluster\"\n",
    "\n",
    "try:\n",
    "    compute_target = ComputeTarget(workspace=ws, name=cluster_name)\n",
    "    print('Compute target exists')\n",
    "except ComputeTargetException:\n",
    "    print('Creating a new compute target')\n",
    "    compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_D2_V2', \n",
    "                                                           max_nodes=4)\n",
    "\n",
    "    # create the cluster\n",
    "    compute_target = ComputeTarget.create(ws, cluster_name, compute_config)\n",
    "\n",
    "    # can poll for a minimum number of nodes and for a specific timeout. \n",
    "    # if no min node count is provided it uses the scale settings for the cluster\n",
    "    compute_target.wait_for_completion(show_output=True, min_node_count=None, timeout_in_minutes=20)\n",
    "\n",
    "# use get_status() to get a detailed status for the current cluster. \n",
    "print(compute_target.get_status().serialize())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "gather": {
     "logged": 1598275789986
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from azureml.widgets import RunDetails\n",
    "from azureml.train.sklearn import SKLearn\n",
    "from azureml.train.hyperdrive.run import PrimaryMetricGoal\n",
    "from azureml.train.hyperdrive.policy import BanditPolicy\n",
    "from azureml.train.hyperdrive.sampling import RandomParameterSampling\n",
    "from azureml.train.hyperdrive.runconfig import HyperDriveConfig\n",
    "from azureml.train.hyperdrive.parameter_expressions import uniform\n",
    "from azureml.train.hyperdrive.parameter_expressions import choice\n",
    "import os\n",
    "import shutil\n",
    "\n",
    "# Specify parameter sampler\n",
    "ps = RandomParameterSampling({\n",
    "    \"--C\": choice(0.001, 0.01, 0.1, 1, 10, 100, 1000),\n",
    "    \"--max_iter\": choice(range(80,150))\n",
    "})\n",
    "\n",
    "# Specify a Policy\n",
    "policy = BanditPolicy(slack_factor = 0.1, evaluation_interval = 3, delay_evaluation=5)\n",
    "\n",
    "if \"training\" not in os.listdir():\n",
    "    os.mkdir(\"./training\")\n",
    "\n",
    "# Create a SKLearn estimator for use with train.py\n",
    "shutil.copy('train.py', \"./training\")\n",
    "\n",
    "est = SKLearn(\n",
    "    source_directory = \"./\",\n",
    "    entry_script = \"train.py\",\n",
    "    compute_target = compute_target\n",
    ")\n",
    "\n",
    "\n",
    "# Create a HyperDriveConfig using the estimator, hyperparameter sampler, and policy.\n",
    "hyperdrive_config = HyperDriveConfig(estimator = est,\n",
    "                                    hyperparameter_sampling = ps,\n",
    "                                    policy = policy,\n",
    "                                    primary_metric_name = \"Accuracy\",\n",
    "                                    primary_metric_goal =PrimaryMetricGoal.MAXIMIZE,\n",
    "                                    max_total_runs = 4,\n",
    "                                    max_concurrent_runs = 4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING - If 'script' has been provided here and a script file name has been specified in 'run_config', 'script' provided in ScriptRunConfig initialization will take precedence.\n"
     ]
    }
   ],
   "source": [
    "# Submit your hyperdrive run to the experiment and show run details with the widget.\n",
    "#exp = experiment(ws, name=\"SKLearn_logistic_regression_experiment\")\n",
    "hyperdrive_run = exp.submit(hyperdrive_config)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e16ddda133b7456998ef61f80c787245",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "_HyperDriveWidget(widget_settings={'childWidgetDisplay': 'popup', 'send_telemetry': False, 'log_level': 'INFO'â€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/aml.mini.widget.v1": "{\"status\": \"Failed\", \"workbench_run_details_uri\": \"https://ml.azure.com/experiments/udacity-project/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6?wsid=/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourcegroups/aml-quickstarts-124346/workspaces/quick-starts-ws-124346\", \"run_id\": \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6\", \"run_properties\": {\"run_id\": \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6\", \"created_utc\": \"2020-11-03T13:36:03.30841Z\", \"properties\": {\"primary_metric_config\": \"{\\\"name\\\": \\\"Accuracy\\\", \\\"goal\\\": \\\"maximize\\\"}\", \"resume_from\": \"null\", \"runTemplate\": \"HyperDrive\", \"azureml.runsource\": \"hyperdrive\", \"platform\": \"AML\", \"ContentSnapshotId\": \"63324456-3be4-4d42-92f3-d16a8900c388\"}, \"tags\": {\"_aml_system_max_concurrent_jobs\": \"4\", \"max_concurrent_jobs\": \"4\", \"_aml_system_max_total_jobs\": \"4\", \"max_total_jobs\": \"4\", \"_aml_system_max_duration_minutes\": \"10080\", \"max_duration_minutes\": \"10080\", \"_aml_system_policy_config\": \"{\\\"name\\\": \\\"BANDIT\\\", \\\"properties\\\": {\\\"evaluation_interval\\\": 3, \\\"delay_evaluation\\\": 5, \\\"slack_factor\\\": 0.1}}\", \"policy_config\": \"{\\\"name\\\": \\\"BANDIT\\\", \\\"properties\\\": {\\\"evaluation_interval\\\": 3, \\\"delay_evaluation\\\": 5, \\\"slack_factor\\\": 0.1}}\", \"_aml_system_generator_config\": \"{\\\"name\\\": \\\"RANDOM\\\", \\\"parameter_space\\\": {\\\"--C\\\": [\\\"choice\\\", [[0.001, 0.01, 0.1, 1, 10, 100, 1000]]], \\\"--max_iter\\\": [\\\"choice\\\", [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]]]}}\", \"generator_config\": \"{\\\"name\\\": \\\"RANDOM\\\", \\\"parameter_space\\\": {\\\"--C\\\": [\\\"choice\\\", [[0.001, 0.01, 0.1, 1, 10, 100, 1000]]], \\\"--max_iter\\\": [\\\"choice\\\", [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]]]}}\", \"_aml_system_primary_metric_config\": \"{\\\"name\\\": \\\"Accuracy\\\", \\\"goal\\\": \\\"maximize\\\"}\", \"primary_metric_config\": \"{\\\"name\\\": \\\"Accuracy\\\", \\\"goal\\\": \\\"maximize\\\"}\", \"_aml_system_platform_config\": \"{\\\"ServiceAddress\\\": \\\"https://southcentralus.experiments.azureml.net\\\", \\\"ServiceArmScope\\\": \\\"subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/udacity-project\\\", \\\"SubscriptionId\\\": \\\"25e9e549-bc6b-4c63-bae8-181a9aa56fa7\\\", \\\"ResourceGroupName\\\": \\\"aml-quickstarts-124346\\\", \\\"WorkspaceName\\\": \\\"quick-starts-ws-124346\\\", \\\"ExperimentName\\\": \\\"udacity-project\\\", \\\"Definition\\\": {\\\"Overrides\\\": {\\\"script\\\": \\\"train.py\\\", \\\"arguments\\\": [], \\\"target\\\": \\\"cpu-cluster\\\", \\\"framework\\\": \\\"Python\\\", \\\"communicator\\\": \\\"None\\\", \\\"maxRunDurationSeconds\\\": null, \\\"nodeCount\\\": 1, \\\"environment\\\": {\\\"name\\\": null, \\\"version\\\": null, \\\"environmentVariables\\\": {\\\"EXAMPLE_ENV_VAR\\\": \\\"EXAMPLE_VALUE\\\"}, \\\"python\\\": {\\\"userManagedDependencies\\\": true, \\\"interpreterPath\\\": \\\"python\\\", \\\"condaDependenciesFile\\\": null, \\\"baseCondaEnvironment\\\": null, \\\"condaDependencies\\\": {\\\"name\\\": \\\"project_environment\\\", \\\"dependencies\\\": [\\\"python=3.6.2\\\", {\\\"pip\\\": [\\\"azureml-defaults\\\"]}], \\\"channels\\\": [\\\"anaconda\\\", \\\"conda-forge\\\"]}}, \\\"docker\\\": {\\\"enabled\\\": true, \\\"baseImage\\\": \\\"sklearn:0.20.3-cpu\\\", \\\"baseDockerfile\\\": null, \\\"sharedVolumes\\\": true, \\\"shmSize\\\": \\\"2g\\\", \\\"arguments\\\": [], \\\"baseImageRegistry\\\": {\\\"address\\\": \\\"viennaprivate.azurecr.io\\\", \\\"username\\\": null, \\\"password\\\": null, \\\"registryIdentity\\\": null}, \\\"platform\\\": {\\\"os\\\": \\\"Linux\\\", \\\"architecture\\\": \\\"amd64\\\"}}, \\\"spark\\\": {\\\"repositories\\\": [], \\\"packages\\\": [], \\\"precachePackages\\\": false}, \\\"databricks\\\": {\\\"mavenLibraries\\\": [], \\\"pypiLibraries\\\": [], \\\"rcranLibraries\\\": [], \\\"jarLibraries\\\": [], \\\"eggLibraries\\\": []}, \\\"r\\\": null, \\\"inferencingStackVersion\\\": null}, \\\"history\\\": {\\\"outputCollection\\\": true, \\\"snapshotProject\\\": true, \\\"directoriesToWatch\\\": [\\\"logs\\\"]}, \\\"spark\\\": {\\\"configuration\\\": {\\\"spark.app.name\\\": \\\"Azure ML Experiment\\\", \\\"spark.yarn.maxAppAttempts\\\": 1}}, \\\"hdi\\\": {\\\"yarnDeployMode\\\": \\\"cluster\\\"}, \\\"tensorflow\\\": {\\\"workerCount\\\": 1, \\\"parameterServerCount\\\": 1}, \\\"mpi\\\": {\\\"processCountPerNode\\\": 1, \\\"nodeCount\\\": 1}, \\\"paralleltask\\\": {\\\"maxRetriesPerWorker\\\": 0, \\\"workerCountPerNode\\\": 1, \\\"terminalExitCodes\\\": null}, \\\"dataReferences\\\": {}, \\\"data\\\": {}, \\\"outputData\\\": {}, \\\"sourceDirectoryDataStore\\\": null, \\\"amlcompute\\\": {\\\"vmSize\\\": null, \\\"vmPriority\\\": null, \\\"retainCluster\\\": false, \\\"name\\\": null, \\\"clusterMaxNodeCount\\\": 1}}, \\\"TargetDetails\\\": null, \\\"SnapshotId\\\": \\\"63324456-3be4-4d42-92f3-d16a8900c388\\\", \\\"TelemetryValues\\\": {\\\"amlClientType\\\": \\\"azureml-sdk-train\\\", \\\"amlClientModule\\\": \\\"[Scrubbed]\\\", \\\"amlClientFunction\\\": \\\"[Scrubbed]\\\", \\\"tenantId\\\": \\\"660b3398-b80e-49d2-bc5b-ac1dc93b5254\\\", \\\"amlClientRequestId\\\": \\\"4ac657ca-1e51-4eea-a278-a09b312022e5\\\", \\\"amlClientSessionId\\\": \\\"67ccec81-32bb-4624-9616-461f2a5c0f0e\\\", \\\"subscriptionId\\\": \\\"25e9e549-bc6b-4c63-bae8-181a9aa56fa7\\\", \\\"estimator\\\": \\\"SKLearn\\\", \\\"samplingMethod\\\": \\\"RANDOM\\\", \\\"terminationPolicy\\\": \\\"Bandit\\\", \\\"primaryMetricGoal\\\": \\\"maximize\\\", \\\"maxTotalRuns\\\": 4, \\\"maxConcurrentRuns\\\": 4, \\\"maxDurationMinutes\\\": 10080, \\\"vmSize\\\": null}}}\", \"platform_config\": \"{\\\"ServiceAddress\\\": \\\"https://southcentralus.experiments.azureml.net\\\", \\\"ServiceArmScope\\\": \\\"subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/udacity-project\\\", \\\"SubscriptionId\\\": \\\"25e9e549-bc6b-4c63-bae8-181a9aa56fa7\\\", \\\"ResourceGroupName\\\": \\\"aml-quickstarts-124346\\\", \\\"WorkspaceName\\\": \\\"quick-starts-ws-124346\\\", \\\"ExperimentName\\\": \\\"udacity-project\\\", \\\"Definition\\\": {\\\"Overrides\\\": {\\\"script\\\": \\\"train.py\\\", \\\"arguments\\\": [], \\\"target\\\": \\\"cpu-cluster\\\", \\\"framework\\\": \\\"Python\\\", \\\"communicator\\\": \\\"None\\\", \\\"maxRunDurationSeconds\\\": null, \\\"nodeCount\\\": 1, \\\"environment\\\": {\\\"name\\\": null, \\\"version\\\": null, \\\"environmentVariables\\\": {\\\"EXAMPLE_ENV_VAR\\\": \\\"EXAMPLE_VALUE\\\"}, \\\"python\\\": {\\\"userManagedDependencies\\\": true, \\\"interpreterPath\\\": \\\"python\\\", \\\"condaDependenciesFile\\\": null, \\\"baseCondaEnvironment\\\": null, \\\"condaDependencies\\\": {\\\"name\\\": \\\"project_environment\\\", \\\"dependencies\\\": [\\\"python=3.6.2\\\", {\\\"pip\\\": [\\\"azureml-defaults\\\"]}], \\\"channels\\\": [\\\"anaconda\\\", \\\"conda-forge\\\"]}}, \\\"docker\\\": {\\\"enabled\\\": true, \\\"baseImage\\\": \\\"sklearn:0.20.3-cpu\\\", \\\"baseDockerfile\\\": null, \\\"sharedVolumes\\\": true, \\\"shmSize\\\": \\\"2g\\\", \\\"arguments\\\": [], \\\"baseImageRegistry\\\": {\\\"address\\\": \\\"viennaprivate.azurecr.io\\\", \\\"username\\\": null, \\\"password\\\": null, \\\"registryIdentity\\\": null}, \\\"platform\\\": {\\\"os\\\": \\\"Linux\\\", \\\"architecture\\\": \\\"amd64\\\"}}, \\\"spark\\\": {\\\"repositories\\\": [], \\\"packages\\\": [], \\\"precachePackages\\\": false}, \\\"databricks\\\": {\\\"mavenLibraries\\\": [], \\\"pypiLibraries\\\": [], \\\"rcranLibraries\\\": [], \\\"jarLibraries\\\": [], \\\"eggLibraries\\\": []}, \\\"r\\\": null, \\\"inferencingStackVersion\\\": null}, \\\"history\\\": {\\\"outputCollection\\\": true, \\\"snapshotProject\\\": true, \\\"directoriesToWatch\\\": [\\\"logs\\\"]}, \\\"spark\\\": {\\\"configuration\\\": {\\\"spark.app.name\\\": \\\"Azure ML Experiment\\\", \\\"spark.yarn.maxAppAttempts\\\": 1}}, \\\"hdi\\\": {\\\"yarnDeployMode\\\": \\\"cluster\\\"}, \\\"tensorflow\\\": {\\\"workerCount\\\": 1, \\\"parameterServerCount\\\": 1}, \\\"mpi\\\": {\\\"processCountPerNode\\\": 1, \\\"nodeCount\\\": 1}, \\\"paralleltask\\\": {\\\"maxRetriesPerWorker\\\": 0, \\\"workerCountPerNode\\\": 1, \\\"terminalExitCodes\\\": null}, \\\"dataReferences\\\": {}, \\\"data\\\": {}, \\\"outputData\\\": {}, \\\"sourceDirectoryDataStore\\\": null, \\\"amlcompute\\\": {\\\"vmSize\\\": null, \\\"vmPriority\\\": null, \\\"retainCluster\\\": false, \\\"name\\\": null, \\\"clusterMaxNodeCount\\\": 1}}, \\\"TargetDetails\\\": null, \\\"SnapshotId\\\": \\\"63324456-3be4-4d42-92f3-d16a8900c388\\\", \\\"TelemetryValues\\\": {\\\"amlClientType\\\": \\\"azureml-sdk-train\\\", \\\"amlClientModule\\\": \\\"[Scrubbed]\\\", \\\"amlClientFunction\\\": \\\"[Scrubbed]\\\", \\\"tenantId\\\": \\\"660b3398-b80e-49d2-bc5b-ac1dc93b5254\\\", \\\"amlClientRequestId\\\": \\\"4ac657ca-1e51-4eea-a278-a09b312022e5\\\", \\\"amlClientSessionId\\\": \\\"67ccec81-32bb-4624-9616-461f2a5c0f0e\\\", \\\"subscriptionId\\\": \\\"25e9e549-bc6b-4c63-bae8-181a9aa56fa7\\\", \\\"estimator\\\": \\\"SKLearn\\\", \\\"samplingMethod\\\": \\\"RANDOM\\\", \\\"terminationPolicy\\\": \\\"Bandit\\\", \\\"primaryMetricGoal\\\": \\\"maximize\\\", \\\"maxTotalRuns\\\": 4, \\\"maxConcurrentRuns\\\": 4, \\\"maxDurationMinutes\\\": 10080, \\\"vmSize\\\": null}}}\", \"_aml_system_resume_child_runs\": \"null\", \"resume_child_runs\": \"null\", \"_aml_system_all_jobs_generated\": \"true\", \"all_jobs_generated\": \"true\", \"_aml_system_cancellation_requested\": \"false\", \"cancellation_requested\": \"false\", \"_aml_system_progress_metadata_evaluation_timestamp\": \"\\\"2020-11-03T13:36:04.017356\\\"\", \"progress_metadata_evaluation_timestamp\": \"\\\"2020-11-03T13:36:04.017356\\\"\", \"_aml_system_progress_metadata_digest\": \"\\\"1dddc6a8de7cf87831666524b210183e8d1b183acdde349c9cf4b2d442a412f2\\\"\", \"progress_metadata_digest\": \"\\\"1dddc6a8de7cf87831666524b210183e8d1b183acdde349c9cf4b2d442a412f2\\\"\", \"_aml_system_progress_metadata_active_timestamp\": \"\\\"2020-11-03T13:36:04.017356\\\"\", \"progress_metadata_active_timestamp\": \"\\\"2020-11-03T13:36:04.017356\\\"\", \"_aml_system_HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0\": \"{\\\"--C\\\": 0.1, \\\"--max_iter\\\": 143}\", \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0\": \"{\\\"--C\\\": 0.1, \\\"--max_iter\\\": 143}\", \"_aml_system_HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1\": \"{\\\"--C\\\": 1, \\\"--max_iter\\\": 109}\", \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1\": \"{\\\"--C\\\": 1, \\\"--max_iter\\\": 109}\", \"_aml_system_HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2\": \"{\\\"--C\\\": 0.1, \\\"--max_iter\\\": 95}\", \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2\": \"{\\\"--C\\\": 0.1, \\\"--max_iter\\\": 95}\", \"_aml_system_HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3\": \"{\\\"--C\\\": 100, \\\"--max_iter\\\": 120}\", \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3\": \"{\\\"--C\\\": 100, \\\"--max_iter\\\": 120}\", \"_aml_system_environment_preparation_status\": \"PREPARED\", \"environment_preparation_status\": \"PREPARED\", \"_aml_system_prepare_run_id\": \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_preparation\", \"prepare_run_id\": \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_preparation\"}, \"end_time_utc\": \"2020-11-03T13:43:21.016685Z\", \"status\": \"Failed\", \"log_files\": {\"azureml-logs/hyperdrive.txt\": \"https://mlstrg124346.blob.core.windows.net/azureml/ExperimentRun/dcid.HD_05619965-7ac2-413f-b0f1-a6237a966bf6/azureml-logs/hyperdrive.txt?sv=2019-02-02&sr=b&sig=kZHq0vtxras2AMu7l2Guf5U1lceG3YQNfnsIqlhCupo%3D&st=2020-11-03T13%3A33%3A46Z&se=2020-11-03T21%3A43%3A46Z&sp=r\"}, \"log_groups\": [[\"azureml-logs/hyperdrive.txt\"]], \"run_duration\": \"0:07:17\", \"hyper_parameters\": {\"--C\": [\"choice\", [[0.001, 0.01, 0.1, 1, 10, 100, 1000]]], \"--max_iter\": [\"choice\", [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]]]}}, \"child_runs\": [{\"run_id\": \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1\", \"run_number\": 54, \"metric\": null, \"status\": \"Failed\", \"run_type\": \"azureml.scriptrun\", \"training_percent\": null, \"start_time\": \"2020-11-03T13:41:04.645926Z\", \"end_time\": \"2020-11-03T13:43:12.412758Z\", \"created_time\": \"2020-11-03T13:36:36.271812Z\", \"created_time_dt\": \"2020-11-03T13:36:36.271812Z\", \"duration\": \"0:06:36\", \"hyperdrive_id\": \"05619965-7ac2-413f-b0f1-a6237a966bf6\", \"arguments\": null, \"param_--C\": 1, \"param_--max_iter\": 109}, {\"run_id\": \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3\", \"run_number\": 56, \"metric\": null, \"status\": \"Failed\", \"run_type\": \"azureml.scriptrun\", \"training_percent\": null, \"start_time\": \"2020-11-03T13:41:05.31762Z\", \"end_time\": \"2020-11-03T13:43:06.201833Z\", \"created_time\": \"2020-11-03T13:36:36.308028Z\", \"created_time_dt\": \"2020-11-03T13:36:36.308028Z\", \"duration\": \"0:06:29\", \"hyperdrive_id\": \"05619965-7ac2-413f-b0f1-a6237a966bf6\", \"arguments\": null, \"param_--C\": 100, \"param_--max_iter\": 120}, {\"run_id\": \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2\", \"run_number\": 55, \"metric\": null, \"status\": \"Failed\", \"run_type\": \"azureml.scriptrun\", \"training_percent\": null, \"start_time\": \"2020-11-03T13:41:09.562314Z\", \"end_time\": \"2020-11-03T13:43:05.044016Z\", \"created_time\": \"2020-11-03T13:36:36.296436Z\", \"created_time_dt\": \"2020-11-03T13:36:36.296436Z\", \"duration\": \"0:06:28\", \"hyperdrive_id\": \"05619965-7ac2-413f-b0f1-a6237a966bf6\", \"arguments\": null, \"param_--C\": 0.1, \"param_--max_iter\": 95}, {\"run_id\": \"HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0\", \"run_number\": 53, \"metric\": null, \"status\": \"Failed\", \"run_type\": \"azureml.scriptrun\", \"training_percent\": null, \"start_time\": \"2020-11-03T13:41:07.984821Z\", \"end_time\": \"2020-11-03T13:43:09.025319Z\", \"created_time\": \"2020-11-03T13:36:36.15663Z\", \"created_time_dt\": \"2020-11-03T13:36:36.15663Z\", \"duration\": \"0:06:32\", \"hyperdrive_id\": \"05619965-7ac2-413f-b0f1-a6237a966bf6\", \"arguments\": null, \"param_--C\": 0.1, \"param_--max_iter\": 143}], \"children_metrics\": {\"categories\": null, \"series\": null, \"metricName\": null}, \"run_metrics\": [], \"run_logs\": \"[2020-11-03T13:36:03.568855][API][INFO]Experiment created\\r\\n[2020-11-03T13:36:04.6656650Z][SCHEDULER][INFO]The execution environment is being prepared. Please be patient as it can take a few minutes.\\r\\n[2020-11-03T13:36:04.331976][GENERATOR][INFO]Trying to sample '4' jobs from the hyperparameter space\\r\\n[2020-11-03T13:36:04.682797][GENERATOR][INFO]Successfully sampled '4' jobs, they will soon be submitted to the execution target.\\r\\n[2020-11-03T13:36:35.1804066Z][SCHEDULER][INFO]The execution environment was successfully prepared.\\r\\n[2020-11-03T13:36:35.1811095Z][SCHEDULER][INFO]Scheduling job, id='HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0'\\r\\n[2020-11-03T13:36:35.1844215Z][SCHEDULER][INFO]Scheduling job, id='HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2'\\r\\n[2020-11-03T13:36:35.1852078Z][SCHEDULER][INFO]Scheduling job, id='HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3'\\r\\n[2020-11-03T13:36:35.159265][GENERATOR][INFO]Max number of jobs '4' reached for experiment.\\r\\n[2020-11-03T13:36:35.1823771Z][SCHEDULER][INFO]Scheduling job, id='HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1'\\r\\n[2020-11-03T13:36:35.427547][GENERATOR][INFO]All jobs generated.\\r\\n[2020-11-03T13:36:36.2735736Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0'\\r\\n[2020-11-03T13:36:36.3746953Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1'\\r\\n[2020-11-03T13:36:36.5039878Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2'\\r\\n[2020-11-03T13:36:36.5384637Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3'\\r\\n[2020-11-03T13:41:08.804558][ENFORCER][INFO]Jobs [https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3] do not contain any metrics with the primary metric name at this moment, policy cannot be applied.\\r\\n[2020-11-03T13:41:38.829962][ENFORCER][INFO]Jobs [https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3] do not contain any metrics with the primary metric name at this moment, policy cannot be applied.\\r\\n[2020-11-03T13:42:10.816570][ENFORCER][INFO]Jobs [https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3] do not contain any metrics with the primary metric name at this moment, policy cannot be applied.\\r\\n[2020-11-03T13:42:43.795557][ENFORCER][INFO]Jobs [https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2, https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3] do not contain any metrics with the primary metric name at this moment, policy cannot be applied.\\r\\n[2020-11-03T13:43:20.831394][CONTROLLER][WARNING]User errors were found in at least one of the child runs.\\r\\n[2020-11-03T13:43:21.216750][CONTROLLER][INFO]Experiment was 'ExperimentStatus.RUNNING', is 'ExperimentStatus.FAILED'.\\n\\nError occurred: User errors were found in at least one of the child runs.\\n\", \"graph\": {}, \"widget_settings\": {\"childWidgetDisplay\": \"popup\", \"send_telemetry\": false, \"log_level\": \"INFO\", \"sdk_version\": \"1.16.0\"}, \"loading\": false}"
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "RunId: HD_05619965-7ac2-413f-b0f1-a6237a966bf6\n",
      "Web View: https://ml.azure.com/experiments/udacity-project/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6?wsid=/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourcegroups/aml-quickstarts-124346/workspaces/quick-starts-ws-124346\n",
      "\n",
      "Streaming azureml-logs/hyperdrive.txt\n",
      "=====================================\n",
      "\n",
      "\"<START>[2020-11-03T13:36:03.568855][API][INFO]Experiment created<END>\\n\"<START>[2020-11-03T13:36:04.6656650Z][SCHEDULER][INFO]The execution environment is being prepared. Please be patient as it can take a few minutes.<END>\"<START>[2020-11-03T13:36:04.331976][GENERATOR][INFO]Trying to sample '4' jobs from the hyperparameter space<END>\\n\"\"<START>[2020-11-03T13:36:04.682797][GENERATOR][INFO]Successfully sampled '4' jobs, they will soon be submitted to the execution target.<END>\\n\"\n",
      "\n",
      "Execution Summary\n",
      "=================\n",
      "RunId: HD_05619965-7ac2-413f-b0f1-a6237a966bf6\n",
      "Web View: https://ml.azure.com/experiments/udacity-project/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6?wsid=/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourcegroups/aml-quickstarts-124346/workspaces/quick-starts-ws-124346\n"
     ]
    },
    {
     "ename": "ActivityFailedException",
     "evalue": "ActivityFailedException:\n\tMessage: Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"User errors were found in at least one of the child runs.\",\n        \"details\": [],\n        \"debugInfo\": {\n            \"message\": \"[(https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"severity\\\": null\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with NameError: name 'clean_data' is not defined\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"NameError\\\",\\n            \\\"message\\\": \\\"name 'clean_data' is not defined\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_0/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 20, in <module>\\\\n    x, y = clean_data(ds)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        },\\n        \\\"message_format\\\": null,\\n        \\\"message_parameters\\\": {},\\n        \\\"reference_code\\\": null\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"severity\\\": null\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with NameError: name 'clean_data' is not defined\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"NameError\\\",\\n            \\\"message\\\": \\\"name 'clean_data' is not defined\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_1/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 20, in <module>\\\\n    x, y = clean_data(ds)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        },\\n        \\\"message_format\\\": null,\\n        \\\"message_parameters\\\": {},\\n        \\\"reference_code\\\": null\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"severity\\\": null\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with NameError: name 'clean_data' is not defined\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"NameError\\\",\\n            \\\"message\\\": \\\"name 'clean_data' is not defined\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_2/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 20, in <module>\\\\n    x, y = clean_data(ds)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        },\\n        \\\"message_format\\\": null,\\n        \\\"message_parameters\\\": {},\\n        \\\"reference_code\\\": null\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"severity\\\": null\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with NameError: name 'clean_data' is not defined\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"NameError\\\",\\n            \\\"message\\\": \\\"name 'clean_data' is not defined\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_3/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 20, in <module>\\\\n    x, y = clean_data(ds)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        },\\n        \\\"message_format\\\": null,\\n        \\\"message_parameters\\\": {},\\n        \\\"reference_code\\\": null\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}})]\"\n        },\n        \"messageParameters\": {}\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"Activity Failed:\\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User errors were found in at least one of the child runs.\\\",\\n        \\\"details\\\": [],\\n        \\\"debugInfo\\\": {\\n            \\\"message\\\": \\\"[(https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0, {'error': {\\\\n    \\\\\\\"additional_properties\\\\\\\": {\\\\n        \\\\\\\"componentName\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"additional_properties\\\\\\\": {\\\\n            \\\\\\\"severity\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"User program failed with NameError: name 'clean_data' is not defined\\\\\\\",\\\\n        \\\\\\\"details_uri\\\\\\\": \\\\\\\"https://aka.ms/azureml-known-errors\\\\\\\",\\\\n        \\\\\\\"target\\\\\\\": null,\\\\n        \\\\\\\"details\\\\\\\": [],\\\\n        \\\\\\\"inner_error\\\\\\\": null,\\\\n        \\\\\\\"debug_info\\\\\\\": {\\\\n            \\\\\\\"additional_properties\\\\\\\": {},\\\\n            \\\\\\\"type\\\\\\\": \\\\\\\"NameError\\\\\\\",\\\\n            \\\\\\\"message\\\\\\\": \\\\\\\"name 'clean_data' is not defined\\\\\\\",\\\\n            \\\\\\\"stack_trace\\\\\\\": \\\\\\\"  File \\\\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_0/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\\\"train.py\\\\\\\\\\\\\\\", line 20, in <module>\\\\\\\\n    x, y = clean_data(ds)\\\\\\\\n\\\\\\\",\\\\n            \\\\\\\"inner_exception\\\\\\\": null,\\\\n            \\\\\\\"data\\\\\\\": null,\\\\n            \\\\\\\"error_response\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"message_format\\\\\\\": null,\\\\n        \\\\\\\"message_parameters\\\\\\\": {},\\\\n        \\\\\\\"reference_code\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"correlation\\\\\\\": null,\\\\n    \\\\\\\"environment\\\\\\\": null,\\\\n    \\\\\\\"location\\\\\\\": null,\\\\n    \\\\\\\"time\\\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1, {'error': {\\\\n    \\\\\\\"additional_properties\\\\\\\": {\\\\n        \\\\\\\"componentName\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"additional_properties\\\\\\\": {\\\\n            \\\\\\\"severity\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"User program failed with NameError: name 'clean_data' is not defined\\\\\\\",\\\\n        \\\\\\\"details_uri\\\\\\\": \\\\\\\"https://aka.ms/azureml-known-errors\\\\\\\",\\\\n        \\\\\\\"target\\\\\\\": null,\\\\n        \\\\\\\"details\\\\\\\": [],\\\\n        \\\\\\\"inner_error\\\\\\\": null,\\\\n        \\\\\\\"debug_info\\\\\\\": {\\\\n            \\\\\\\"additional_properties\\\\\\\": {},\\\\n            \\\\\\\"type\\\\\\\": \\\\\\\"NameError\\\\\\\",\\\\n            \\\\\\\"message\\\\\\\": \\\\\\\"name 'clean_data' is not defined\\\\\\\",\\\\n            \\\\\\\"stack_trace\\\\\\\": \\\\\\\"  File \\\\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_1/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\\\"train.py\\\\\\\\\\\\\\\", line 20, in <module>\\\\\\\\n    x, y = clean_data(ds)\\\\\\\\n\\\\\\\",\\\\n            \\\\\\\"inner_exception\\\\\\\": null,\\\\n            \\\\\\\"data\\\\\\\": null,\\\\n            \\\\\\\"error_response\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"message_format\\\\\\\": null,\\\\n        \\\\\\\"message_parameters\\\\\\\": {},\\\\n        \\\\\\\"reference_code\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"correlation\\\\\\\": null,\\\\n    \\\\\\\"environment\\\\\\\": null,\\\\n    \\\\\\\"location\\\\\\\": null,\\\\n    \\\\\\\"time\\\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2, {'error': {\\\\n    \\\\\\\"additional_properties\\\\\\\": {\\\\n        \\\\\\\"componentName\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"additional_properties\\\\\\\": {\\\\n            \\\\\\\"severity\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"User program failed with NameError: name 'clean_data' is not defined\\\\\\\",\\\\n        \\\\\\\"details_uri\\\\\\\": \\\\\\\"https://aka.ms/azureml-known-errors\\\\\\\",\\\\n        \\\\\\\"target\\\\\\\": null,\\\\n        \\\\\\\"details\\\\\\\": [],\\\\n        \\\\\\\"inner_error\\\\\\\": null,\\\\n        \\\\\\\"debug_info\\\\\\\": {\\\\n            \\\\\\\"additional_properties\\\\\\\": {},\\\\n            \\\\\\\"type\\\\\\\": \\\\\\\"NameError\\\\\\\",\\\\n            \\\\\\\"message\\\\\\\": \\\\\\\"name 'clean_data' is not defined\\\\\\\",\\\\n            \\\\\\\"stack_trace\\\\\\\": \\\\\\\"  File \\\\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_2/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\\\"train.py\\\\\\\\\\\\\\\", line 20, in <module>\\\\\\\\n    x, y = clean_data(ds)\\\\\\\\n\\\\\\\",\\\\n            \\\\\\\"inner_exception\\\\\\\": null,\\\\n            \\\\\\\"data\\\\\\\": null,\\\\n            \\\\\\\"error_response\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"message_format\\\\\\\": null,\\\\n        \\\\\\\"message_parameters\\\\\\\": {},\\\\n        \\\\\\\"reference_code\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"correlation\\\\\\\": null,\\\\n    \\\\\\\"environment\\\\\\\": null,\\\\n    \\\\\\\"location\\\\\\\": null,\\\\n    \\\\\\\"time\\\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3, {'error': {\\\\n    \\\\\\\"additional_properties\\\\\\\": {\\\\n        \\\\\\\"componentName\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"additional_properties\\\\\\\": {\\\\n            \\\\\\\"severity\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"User program failed with NameError: name 'clean_data' is not defined\\\\\\\",\\\\n        \\\\\\\"details_uri\\\\\\\": \\\\\\\"https://aka.ms/azureml-known-errors\\\\\\\",\\\\n        \\\\\\\"target\\\\\\\": null,\\\\n        \\\\\\\"details\\\\\\\": [],\\\\n        \\\\\\\"inner_error\\\\\\\": null,\\\\n        \\\\\\\"debug_info\\\\\\\": {\\\\n            \\\\\\\"additional_properties\\\\\\\": {},\\\\n            \\\\\\\"type\\\\\\\": \\\\\\\"NameError\\\\\\\",\\\\n            \\\\\\\"message\\\\\\\": \\\\\\\"name 'clean_data' is not defined\\\\\\\",\\\\n            \\\\\\\"stack_trace\\\\\\\": \\\\\\\"  File \\\\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_3/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\\\"train.py\\\\\\\\\\\\\\\", line 20, in <module>\\\\\\\\n    x, y = clean_data(ds)\\\\\\\\n\\\\\\\",\\\\n            \\\\\\\"inner_exception\\\\\\\": null,\\\\n            \\\\\\\"data\\\\\\\": null,\\\\n            \\\\\\\"error_response\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"message_format\\\\\\\": null,\\\\n        \\\\\\\"message_parameters\\\\\\\": {},\\\\n        \\\\\\\"reference_code\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"correlation\\\\\\\": null,\\\\n    \\\\\\\"environment\\\\\\\": null,\\\\n    \\\\\\\"location\\\\\\\": null,\\\\n    \\\\\\\"time\\\\\\\": {}\\\\n}})]\\\"\\n        },\\n        \\\"messageParameters\\\": {}\\n    },\\n    \\\"time\\\": \\\"0001-01-01T00:00:00.000Z\\\"\\n}\"\n    }\n}",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mActivityFailedException\u001b[0m                   Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-5-4cb88647f561>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mRunDetails\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhyperdrive_run\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mhyperdrive_run\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_completion\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mshow_output\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/run.py\u001b[0m in \u001b[0;36mwait_for_completion\u001b[0;34m(self, show_output, wait_post_processing, raise_on_error)\u001b[0m\n\u001b[1;32m    714\u001b[0m                     \u001b[0mfile_handle\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstdout\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    715\u001b[0m                     \u001b[0mwait_post_processing\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mwait_post_processing\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 716\u001b[0;31m                     raise_on_error=raise_on_error)\n\u001b[0m\u001b[1;32m    717\u001b[0m                 \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_details\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    718\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mKeyboardInterrupt\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/run.py\u001b[0m in \u001b[0;36m_stream_run_output\u001b[0;34m(self, file_handle, wait_post_processing, raise_on_error)\u001b[0m\n\u001b[1;32m    955\u001b[0m                 \u001b[0mfile_handle\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrite\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"\\n\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    956\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 957\u001b[0;31m                 \u001b[0;32mraise\u001b[0m \u001b[0mActivityFailedException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0merror_details\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mjson\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdumps\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mindent\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m4\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    958\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    959\u001b[0m         \u001b[0mfile_handle\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrite\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"\\n\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mActivityFailedException\u001b[0m: ActivityFailedException:\n\tMessage: Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"User errors were found in at least one of the child runs.\",\n        \"details\": [],\n        \"debugInfo\": {\n            \"message\": \"[(https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"severity\\\": null\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with NameError: name 'clean_data' is not defined\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"NameError\\\",\\n            \\\"message\\\": \\\"name 'clean_data' is not defined\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_0/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 20, in <module>\\\\n    x, y = clean_data(ds)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        },\\n        \\\"message_format\\\": null,\\n        \\\"message_parameters\\\": {},\\n        \\\"reference_code\\\": null\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"severity\\\": null\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with NameError: name 'clean_data' is not defined\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"NameError\\\",\\n            \\\"message\\\": \\\"name 'clean_data' is not defined\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_1/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 20, in <module>\\\\n    x, y = clean_data(ds)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        },\\n        \\\"message_format\\\": null,\\n        \\\"message_parameters\\\": {},\\n        \\\"reference_code\\\": null\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"severity\\\": null\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with NameError: name 'clean_data' is not defined\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"NameError\\\",\\n            \\\"message\\\": \\\"name 'clean_data' is not defined\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_2/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 20, in <module>\\\\n    x, y = clean_data(ds)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        },\\n        \\\"message_format\\\": null,\\n        \\\"message_parameters\\\": {},\\n        \\\"reference_code\\\": null\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"severity\\\": null\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with NameError: name 'clean_data' is not defined\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"NameError\\\",\\n            \\\"message\\\": \\\"name 'clean_data' is not defined\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_3/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 20, in <module>\\\\n    x, y = clean_data(ds)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        },\\n        \\\"message_format\\\": null,\\n        \\\"message_parameters\\\": {},\\n        \\\"reference_code\\\": null\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}})]\"\n        },\n        \"messageParameters\": {}\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"Activity Failed:\\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User errors were found in at least one of the child runs.\\\",\\n        \\\"details\\\": [],\\n        \\\"debugInfo\\\": {\\n            \\\"message\\\": \\\"[(https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0, {'error': {\\\\n    \\\\\\\"additional_properties\\\\\\\": {\\\\n        \\\\\\\"componentName\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"additional_properties\\\\\\\": {\\\\n            \\\\\\\"severity\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"User program failed with NameError: name 'clean_data' is not defined\\\\\\\",\\\\n        \\\\\\\"details_uri\\\\\\\": \\\\\\\"https://aka.ms/azureml-known-errors\\\\\\\",\\\\n        \\\\\\\"target\\\\\\\": null,\\\\n        \\\\\\\"details\\\\\\\": [],\\\\n        \\\\\\\"inner_error\\\\\\\": null,\\\\n        \\\\\\\"debug_info\\\\\\\": {\\\\n            \\\\\\\"additional_properties\\\\\\\": {},\\\\n            \\\\\\\"type\\\\\\\": \\\\\\\"NameError\\\\\\\",\\\\n            \\\\\\\"message\\\\\\\": \\\\\\\"name 'clean_data' is not defined\\\\\\\",\\\\n            \\\\\\\"stack_trace\\\\\\\": \\\\\\\"  File \\\\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_0/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_0/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\\\"train.py\\\\\\\\\\\\\\\", line 20, in <module>\\\\\\\\n    x, y = clean_data(ds)\\\\\\\\n\\\\\\\",\\\\n            \\\\\\\"inner_exception\\\\\\\": null,\\\\n            \\\\\\\"data\\\\\\\": null,\\\\n            \\\\\\\"error_response\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"message_format\\\\\\\": null,\\\\n        \\\\\\\"message_parameters\\\\\\\": {},\\\\n        \\\\\\\"reference_code\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"correlation\\\\\\\": null,\\\\n    \\\\\\\"environment\\\\\\\": null,\\\\n    \\\\\\\"location\\\\\\\": null,\\\\n    \\\\\\\"time\\\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1, {'error': {\\\\n    \\\\\\\"additional_properties\\\\\\\": {\\\\n        \\\\\\\"componentName\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"additional_properties\\\\\\\": {\\\\n            \\\\\\\"severity\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"User program failed with NameError: name 'clean_data' is not defined\\\\\\\",\\\\n        \\\\\\\"details_uri\\\\\\\": \\\\\\\"https://aka.ms/azureml-known-errors\\\\\\\",\\\\n        \\\\\\\"target\\\\\\\": null,\\\\n        \\\\\\\"details\\\\\\\": [],\\\\n        \\\\\\\"inner_error\\\\\\\": null,\\\\n        \\\\\\\"debug_info\\\\\\\": {\\\\n            \\\\\\\"additional_properties\\\\\\\": {},\\\\n            \\\\\\\"type\\\\\\\": \\\\\\\"NameError\\\\\\\",\\\\n            \\\\\\\"message\\\\\\\": \\\\\\\"name 'clean_data' is not defined\\\\\\\",\\\\n            \\\\\\\"stack_trace\\\\\\\": \\\\\\\"  File \\\\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_1/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_1/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\\\"train.py\\\\\\\\\\\\\\\", line 20, in <module>\\\\\\\\n    x, y = clean_data(ds)\\\\\\\\n\\\\\\\",\\\\n            \\\\\\\"inner_exception\\\\\\\": null,\\\\n            \\\\\\\"data\\\\\\\": null,\\\\n            \\\\\\\"error_response\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"message_format\\\\\\\": null,\\\\n        \\\\\\\"message_parameters\\\\\\\": {},\\\\n        \\\\\\\"reference_code\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"correlation\\\\\\\": null,\\\\n    \\\\\\\"environment\\\\\\\": null,\\\\n    \\\\\\\"location\\\\\\\": null,\\\\n    \\\\\\\"time\\\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2, {'error': {\\\\n    \\\\\\\"additional_properties\\\\\\\": {\\\\n        \\\\\\\"componentName\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"additional_properties\\\\\\\": {\\\\n            \\\\\\\"severity\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"User program failed with NameError: name 'clean_data' is not defined\\\\\\\",\\\\n        \\\\\\\"details_uri\\\\\\\": \\\\\\\"https://aka.ms/azureml-known-errors\\\\\\\",\\\\n        \\\\\\\"target\\\\\\\": null,\\\\n        \\\\\\\"details\\\\\\\": [],\\\\n        \\\\\\\"inner_error\\\\\\\": null,\\\\n        \\\\\\\"debug_info\\\\\\\": {\\\\n            \\\\\\\"additional_properties\\\\\\\": {},\\\\n            \\\\\\\"type\\\\\\\": \\\\\\\"NameError\\\\\\\",\\\\n            \\\\\\\"message\\\\\\\": \\\\\\\"name 'clean_data' is not defined\\\\\\\",\\\\n            \\\\\\\"stack_trace\\\\\\\": \\\\\\\"  File \\\\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_2/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_2/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\\\"train.py\\\\\\\\\\\\\\\", line 20, in <module>\\\\\\\\n    x, y = clean_data(ds)\\\\\\\\n\\\\\\\",\\\\n            \\\\\\\"inner_exception\\\\\\\": null,\\\\n            \\\\\\\"data\\\\\\\": null,\\\\n            \\\\\\\"error_response\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"message_format\\\\\\\": null,\\\\n        \\\\\\\"message_parameters\\\\\\\": {},\\\\n        \\\\\\\"reference_code\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"correlation\\\\\\\": null,\\\\n    \\\\\\\"environment\\\\\\\": null,\\\\n    \\\\\\\"location\\\\\\\": null,\\\\n    \\\\\\\"time\\\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/25e9e549-bc6b-4c63-bae8-181a9aa56fa7/resourceGroups/aml-quickstarts-124346/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-124346/experiments/**SCRUBBED**/runs/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3, {'error': {\\\\n    \\\\\\\"additional_properties\\\\\\\": {\\\\n        \\\\\\\"componentName\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"additional_properties\\\\\\\": {\\\\n            \\\\\\\"severity\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"User program failed with NameError: name 'clean_data' is not defined\\\\\\\",\\\\n        \\\\\\\"details_uri\\\\\\\": \\\\\\\"https://aka.ms/azureml-known-errors\\\\\\\",\\\\n        \\\\\\\"target\\\\\\\": null,\\\\n        \\\\\\\"details\\\\\\\": [],\\\\n        \\\\\\\"inner_error\\\\\\\": null,\\\\n        \\\\\\\"debug_info\\\\\\\": {\\\\n            \\\\\\\"additional_properties\\\\\\\": {},\\\\n            \\\\\\\"type\\\\\\\": \\\\\\\"NameError\\\\\\\",\\\\n            \\\\\\\"message\\\\\\\": \\\\\\\"name 'clean_data' is not defined\\\\\\\",\\\\n            \\\\\\\"stack_trace\\\\\\\": \\\\\\\"  File \\\\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-124346/azureml/hd_05619965-7ac2-413f-b0f1-a6237a966bf6_3/mounts/workspaceblobstore/azureml/HD_05619965-7ac2-413f-b0f1-a6237a966bf6_3/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\\\"train.py\\\\\\\\\\\\\\\", line 20, in <module>\\\\\\\\n    x, y = clean_data(ds)\\\\\\\\n\\\\\\\",\\\\n            \\\\\\\"inner_exception\\\\\\\": null,\\\\n            \\\\\\\"data\\\\\\\": null,\\\\n            \\\\\\\"error_response\\\\\\\": null\\\\n        },\\\\n        \\\\\\\"message_format\\\\\\\": null,\\\\n        \\\\\\\"message_parameters\\\\\\\": {},\\\\n        \\\\\\\"reference_code\\\\\\\": null\\\\n    },\\\\n    \\\\\\\"correlation\\\\\\\": null,\\\\n    \\\\\\\"environment\\\\\\\": null,\\\\n    \\\\\\\"location\\\\\\\": null,\\\\n    \\\\\\\"time\\\\\\\": {}\\\\n}})]\\\"\\n        },\\n        \\\"messageParameters\\\": {}\\n    },\\n    \\\"time\\\": \\\"0001-01-01T00:00:00.000Z\\\"\\n}\"\n    }\n}"
     ]
    }
   ],
   "source": [
    "RunDetails(hyperdrive_run).show()\n",
    "hyperdrive_run.wait_for_completion(show_output=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "AssertionError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-3e9f3ac98364>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32massert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhyperdrive_run\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"Completed\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "assert(hyperdrive_run.get_status() == \"Completed\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "gather": {
     "logged": 1598276310862
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "import joblib\n",
    "# Get your best run and save the model from that run.\n",
    "\n",
    "best_run = hyperdrive_run.get_best_run_by_primary_metric()\n",
    "print(best_run.get_details()['runDefinition']['arguments'])\n",
    "print(best_run.get_file_names())\n",
    "best_run_metrics = best_run.get_metrics()\n",
    "print('\\n Accuracy:', best_run_metrics['Accuracy'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = best_run.register_model(model_name='udacity_project_sklearn_logistic_regression', model_path='outputs/model.joblib')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from azureml.data.dataset_factory import TabularDatasetFactory\n",
    "from azureml.core import Dataset\n",
    "\n",
    "# Create TabularDataset using TabularDatasetFactory\n",
    "# Data is available at: \n",
    "# \"https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv\"\n",
    "\n",
    "ds = TabularDatasetFactory.from_delimited_files(path = \"https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "gather": {
     "logged": 1598275726969
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from train import clean_data\n",
    "\n",
    "# Use the clean_data function to clean your data.\n",
    "x, y = clean_data(ds)\n",
    "\n",
    "# Split into train and test\n",
    "from sklearn.model_selection import train_test_split\n",
    "import pandas as pd\n",
    "x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, shuffle=True)\n",
    "\n",
    "df_train = pd.concat([x_train, y_train], axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train.to_csv('training/training_data.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "exp = Experiment(workspace=ws, name=\"AutoML-test\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "datastore = ws.get_default_datastore()\n",
    "datastore"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "datastore.upload(src_dir='training/', target_path='data/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_dataset = Dataset.Tabular.from_delimited_files(path=[(dtaastore, ('data/training_data.csv'))])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "gather": {
     "logged": 1598275665403
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from azureml.train.automl import AutoMLConfig\n",
    "\n",
    "# Set parameters for AutoMLConfig\n",
    "# NOTE: DO NOT CHANGE THE experiment_timeout_minutes PARAMETER OR YOUR INSTANCE WILL TIME OUT.\n",
    "# If you wish to run the experiment longer, you will need to run this notebook in your own\n",
    "# Azure tenant, which will incur personal costs.\n",
    "automl_config = AutoMLConfig(\n",
    "    experiment_timeout_minutes=30,\n",
    "    task=\"classification\",\n",
    "    primary_metric=\"accuracy\",\n",
    "    training_data=train_dataset,\n",
    "    label_column_name=\"y\",\n",
    "    n_cross_validations=5,\n",
    "    compute_target = compute_target,\n",
    "    iterations = 40,\n",
    "    max_concurrent_iterations = 6,\n",
    "    max_cores_per_iteration = -1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "# Submit your automl run\n",
    "run = exp.submit(config=automl_config, show_output=True)\n",
    "RunDetails(run).show()\n",
    "run.wait_for_completion(show_output=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Retrieve and save your best automl model.\n",
    "best_run, best_model = run.get_output()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "run.register_model(model_name = \"automl_udacity_project\", model_path = './outputs/')\n",
    "print(best_model._final_estimator)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "compute_target_delete()"
   ]
  }
 ],
 "metadata": {
  "kernel_info": {
   "name": "python3-azureml"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  },
  "nteract": {
   "version": "nteract-front-end@1.0.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
